#include <stdio.h>
#include <stdlib.h>

#include "global.h"
#include "debug.h"
#include "funcs.h"
#ifdef _STRING_H
#error "Do not #include <string.h>. You will get a ZERO."
#endif

#ifdef _STRINGS_H
#error "Do not #include <strings.h>. You will get a ZERO."
#endif

#ifdef _CTYPE_H
#error "Do not #include <ctype.h>. You will get a ZERO."
#endif

int main(int argc, char **argv)
{   
    // start_transmission(); 
    // end_transmission();  
    // print_magic();   
    // fputc(0x00, stdout); 
    // print_depth(0);  
    // print_size(16);      
    // validargs(argc, argv); 
    // global_options = 0x02;   
    // if(global_options == 0x02){
    // path_init("rsrc/testdir/dir/goodbye"); 
    // serialize_file(2, 9);}else{  
    //     path_init("temp"); 
    //     printf("%d", deserialize_file(2)); 
    // } 
    // path_init("rsrc/testdir"); 
    // serialize_directory(1);      


    // path_init("paste/dump"); 
    // deserialize_directory(1); 
    // path_init("temp/hello1");   
    // global_options = 0xc; 
    // deserialize_file(2); 
    // path_init("rsrc/testdir"); 
    // serialize(); 
    // str_copy(NULL, name_buf); 
    // printf("%s\n", name_buf);  
    // printf("%d",str_Eql("-ha", "-h"));  
    // path_init("DIR/BANANA/POKEMON/"); 
    // printf("%s\n", path_buf);   
    // printf("%d\n", path_length);  
    // path_pop();  
    // printf("%s\n", path_buf);   
    // printf("%d\n", path_length);   
    // path_pop(); 
    // printf("%s\n", path_buf);   
    // printf("%d\n", path_length);    
    // path_pop(); 
    // printf("%s\n", path_buf);   
    // printf("%d\n", path_length); 
    // if(path_pop()){
    //     printf("ERROR CAUGHT\n"); 
    // }  

    // path_push("AABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAABBAAAAAAaaaaaaaafdsafadsfafsafasfrerewrwerewrewrwerewrewrwerwerwerewrwerwerwerewrwerewrwrewrewrewrewrewrewrewrewrewrewrwerewrewrewrewrewrwerewww");   
    // printf("%s\n", path_buf);   
    // printf("%d\n", path_length);  
    // path_pop();  
    // printf("%s\n", path_buf);   
    // printf("%d\n", path_length);    
    // path_init("rsrc/testdir/dir/goodbye"); 
    // serialize_file(2, 9);  
    //deserialize_file(2); 
    // printf("%d ", deserialize_file(2));  

    int ret;
    if(validargs(argc, argv)){
        USAGE(*argv, EXIT_FAILURE); 
    }
    if(global_options & 0x1){
        USAGE(*argv, EXIT_SUCCESS); 
    }  

    if(global_options & 0x02){ 
        if(serialize() == -1){ 
            fprintf(stderr, "Serialize Failed!");  
            return EXIT_FAILURE; 
        }else{ 
            return EXIT_SUCCESS; 
        }
    } 
    if(global_options & 0x04){ 
        if(deserialize() == -1){ 
            fprintf(stderr, "Deserialize Failed");  
            return EXIT_FAILURE; 
        }else{ 
            return EXIT_SUCCESS; 
        }
    }   

    return EXIT_SUCCESS;      
    // global_options = 0xc; 
    // path_init("temp/goodbye"); 
    // deserialize_file(2);   
    // path_init("paste");  
    // path_init("rsrc/testdir/hello");  
    // serialize_file() 
    // path_init("paste"); 
    // printf("%d",deserialize_directory(1)); 
}

/*
 * Just a reminder: All non-main functions should
 * be in another file not named main.c
 */
